version: "3.9"

services:
  django:
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django-app:/app
    env_file:
      - .env.dev
    environment:
      DJANGO_SETTINGS_MODULE: ai.settings.dev
    ports:
      - "8000:8000"

  fastapi:
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - ./fastapi-app:/app
    env_file:
      - .env.dev
    ports:
      - "8001:8001"
